INSERT INTO trilha (t_descricao, t_livro_id) VALUES 
  ('Prova de Ingresso', (SELECT l_id FROM livro WHERE l_descricao = 'Prova de Ingresso' AND l_clube = 'URSINHO')),
  ('Trilha do grau alegria', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Trilha da ovelinha um', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Caminhada do elefante um', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Trilha da ovelinha dois', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Caminhada do elefante dois', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Trilha da ovelha três', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Caminhada do elefante três', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Trilha da ovelha quatro', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Caminhada do elefante quatro', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO')),
  ('Celebração da alegria', (SELECT l_id FROM livro WHERE l_descricao = 'Celebrações de alegria' AND l_clube = 'URSINHO'));


INSERT INTO trilha (t_descricao, t_livro_id) VALUES 
  ('Prova de Ingresso', (SELECT l_id FROM livro WHERE l_descricao = 'Prova de Ingresso' AND l_clube = 'FAISCA')),
  ('Trilha do grau', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 1', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 2', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 3', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 4', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Verde 1', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Verde 2', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Verde 3', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Joia Verde 4', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Campina do Saltador', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Saltador' AND l_clube = 'FAISCA')),
  ('Trilha do grau', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 1', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 2', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 3', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 4', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Verde 1', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Verde 2', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Verde 3', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Joia Verde 4', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Campina do Caminhante', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Caminhante' AND l_clube = 'FAISCA')),
  ('Trilha do grau', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 1', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 2', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 3', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Vermelha 4', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Verde 1', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Verde 2', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Verde 3', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Joia Verde 4', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA')),
  ('Campina do Escalador', (SELECT l_id FROM livro WHERE l_descricao = 'Manual Escalador' AND l_clube = 'FAISCA'));